[book]
title = "lxbeyond 的小说书架"
authors = ["lxbeyond"]
language = "zh"
src = "src"
description = "lxbeyond 的原创小说合集"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/lxbeyond/novel-book"
additional-css = ["theme/custom.css"]
additional-js = ["theme/sidebar-filter.js"]
